apiVersion: v1
kind: Pod
metadata:
 name: echo
 labels:
  app: echo
spec:
 containers:
 - name: echo
   image: enchanted13th/echo
   ports:
   - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
 name: echo
spec:
 type: NodePort
 selector:
  app: echo
 ports:
 - name: http
   port: 80
