apiVersion: v1
kind: Pod
metadata:
 name: pod-1
spec:
 nodeSelector:
  kubernetes.io/hostname: k8s-node1
 containers:
 - name: container
   image: tmkube/init

---

apiVersion: v1
kind: Pod
metadata:
 name: pod-2
spec:
 containers:
 - name: container
   image: tmkube/init
   resources:
    requests:
     memory: 1.5Gi
    limits:
     memory: 2Gi

---

apiVersion: v1
kind: Pod
metadata:
 name: pod-3
spec:
 containers:
 - name: container
   image: tmkube/init
   resources:
    requests:
     memory: 0.5Gi
    limits:
     memory: 0.5Gi
