apiVersion: v1
kind: Pod
metadata:
 name: pod-1
 labels:
  type: web
  lo: dev
spec:
 containers:
 - name: container
   image: tmkube/init

---

apiVersion: v1
kind: Pod
metadata:
 name: pod-2
 labels:
  type: db
  lo: dev
spec:
 containers:
 - name: container
   image: tmkube/init

---

apiVersion: v1
kind: Pod
metadata:
 name: pod-3
 labels:
  type: server
  lo: dev
spec:
 containers:
 - name: container
   image: tmkube/init

---

apiVersion: v1
kind: Pod
metadata:
 name: pod-4
 labels:
  type: web
  lo: production
spec:
 containers:
 - name: container
   image: tmkube/init

---

apiVersion: v1
kind: Pod
metadata:
 name: pod-5
 labels:
  type: db
  lo: production
spec:
 containers:
 - name: container
   image: tmkube/init

---

apiVersion: v1
kind: Pod
metadata:
 name: pod-6
 labels:
  type: server
  lo: production
spec:
 containers:
 - name: container
   image: tmkube/init

---

apiVersion: v1
kind: Service
metadata:
 name: svc-for-web
spec:
 selector:
  type: web
 ports:
 - port: 8080

---


apiVersion: v1
kind: Service
metadata:
 name: svc-for-prod
spec:
 selector:
  lo: production
 ports:
 - port: 8080
