apiVersion: v1
kind: Pod
metadata:
 name: pod-1
 labels:
  app: pod
spec:
 nodeSelector:
  kubernetes.io/hostname: k8s-node1
 containers:
 - name: container
   image: tmkube/app
   ports:
   - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
 name: svc-1
spec:
 selector:
  app: pod
 ports:
 - port: 9000
   targetPort: 8080
 type: LoadBalancer
