apiVersion: v1
kind: Service
metadata:
 name: svc-2
 namespace: nm-2
spec:
 ports:
 - port: 9000
   targetPort: 8080
   nodePort: 30001
 type: NodePort

---

apiVersion: v1
kind: Service
metadata:
 name: svc-2
 namespace: nm-1
spec:
 ports:
 - port: 9000
   targetPort: 8080
   nodePort: 30001
 type: NodePort
