apiVersion: v1
kind: Pod
metadata:
 name: pod-mount
spec:
 containers:
 - name: container
   image: tmkube/init
   volumeMounts:
   - name: file-volume
     mountPath: /mount
 volumes:
 - name: file-volume
   configMap:
    name: cm-file
